# Generated by Django 2.0 on 2018-01-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdropdown',
            name='time',
            field=models.CharField(choices=[('9:35 - 10:30', '9:35 - 10:30'), ('default', 'default')], default='DEFAULT_VALUE', max_length=200),
        ),
        migrations.AlterField(
            model_name='subjectdropdown',
            name='subject',
            field=models.CharField(choices=[('COMP', 'Computer Science'), ('COGS', 'Cognitive Science')], max_length=200),
        ),
    ]
