# Generated by Django 2.0 on 2018-01-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_auto_20180129_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('COMP', 'Computer Science'), ('COGS', 'Cognitive Science')], max_length=40)),
                ('time', models.CharField(choices=[('9:35 - 10:30', '9:35 - 10:30'), ('default', 'default')], default='DEFAULT_VALUE', max_length=30)),
                ('isgn', models.IntegerField()),
                ('instructor', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='SubjectDropdown',
        ),
    ]
